---@diagnostic disable: undefined-global
-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.s
-- icon = "",
-- icon = "",
-- icon = "﯑",
-- 
-- ❄
-- ☄
-- 
vim.g.use_nerd_icons = false
if vim.fn.has("mac") == 1 or vim.g.use_nerd_icons then
  -- elseif vim.fn.has("mac") == 1 then
  return {
    kind = {
      Boolean = "󰨙 ",
      Class = "",
      Constructor = "", -- Constructor = "",
      Color = "",
      Control = " ",
      Constant = "", -- Constant = " ",
      Enum = "",
      EnumMember = "",
      Event = "", -- Event = " ",
      Field = "ﰠ", -- Field = " ",
      File = "",
      Folder = "",
      Function = "", -- Function = "",
      Interface = " ", -- Interface = "",
      Keyword = "", -- Keyword = "",
      Method = " ", -- Method = "",
      Module = "", -- Module = "",
      Namespace = "󰦮 ",
      Null = " ",
      Number = "󰎠 ",
      Object = " ",
      Operator = " ", -- Operator = "", -- Operator = " ",
      Property = "", -- Property = " ",
      Reference = "",
      Snippet = "", -- Snippet = "",
      String = "", -- String = " ", String = " ",
      Struct = "󰆼 ", -- Struct = "",
      Text = " ", -- Text = "",
      TypeParameter = " ", -- TypeParameter = "",
      Unit = " ", -- Unit = "",
      Unknown = " ",
      Value = "", -- Value = " ",
      Variable = "󰀫 ", -- Variable = "", -- Variable = "",
    },
    type = {
      Array = "", -- Array = " ",
      Number = "󰎠 ", -- Number = "",
      String = "", -- String = " ",
      Boolean = "󰨙 ", -- Boolean = "蘒", Boolean = " ",
      Object = " ", -- Object = "",
    },
    documents = {
      File = "",
      Files = "",
      Folder = " ", -- Folder = "",
      OpenFolder = "",
    },
    git = {
      commit = "󰜘 ", -- used by git log
      staged = "●", -- staged changes. always overrides the type icons
      added = "",
      deleted = "",
      ignored = " ",
      modified = "○",
      renamed = "",
      unmerged = " ",
      untracked = "?",
      Add = "",
      Mod = "",
      Remove = "",
      Ignore = "",
      Rename = "",
      Diff = "",
      Repo = "",
      Octoface = "",
    },
    ui = {
      live = "󰐰 ",
      hidden = "h",
      ignored = "i",
      follow = "f",
      selected = "● ",
      unselected = "○ ",
      -- selected = " ",
      ArrowClosed = "",
      ArrowOpen = "",
      Lock = "",
      Circle = "",
      BigCircle = "",
      BigUnfilledCircle = "",
      Close = "",
      NewFile = "",
      Search = "",
      Lightbulb = "",
      Project = "",
      Dashboard = "",
      -- History = "",
      History = " ",
      Comment = "",
      Bug = "",
      Code = "",
      Telescope = "",
      Gear = "",
      Package = "",
      List = "",
      SignIn = "",
      SignOut = "",
      Check = "",
      Fire = "",
      Note = "",
      BookMark = "",
      Pencil = "",
      -- ChevronRight = "",
      ChevronRight = ">",
      Table = "",
      Calendar = "",
      CloudDownload = "",
      nowait = "󰓅 ",
    },
    undo = {
      saved = " ",
    },
    diagnostics = {
      Error = "",
      Warning = "",
      Information = "",
      Question = "",
      Hint = "",
    },
    lsp = {
      unavailable = "",
      enabled = " ",
      disabled = " ",
      attached = "󰖩 ",
    },
    misc = {
      Robot = "ﮧ",
      Squirrel = "",
      Tag = "",
      Watch = "",
      Smiley = "ﲃ",
      Package = "",
      Circuioard = "",
    },
  }
else
  --   פּ ﯟ   蘒練 some other good icons
  return {
    kind = {
      Text = " ",
      Method = " ",
      Function = "",
      Constructor = " ",
      Field = " ",
      Variable = " ",
      Class = " ",
      Interface = " ",
      Module = " ",
      Property = " ",
      Unit = " ",
      Value = " ",
      Enum = " ",
      Keyword = " ",
      Snippet = " ",
      Color = " ",
      File = " ",
      Reference = " ",
      Folder = " ",
      EnumMember = " ",
      Constant = " ",
      Struct = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
      Misc = " ",
    },
    type = {
      Array = " ",
      Number = " ",
      String = " ",
      Boolean = " ",
      Object = " ",
    },
    documents = {
      File = " ",
      Files = " ",
      Folder = " ",
      OpenFolder = " ",
    },
    git = {
      Add = " ",
      Mod = " ",
      Remove = " ",
      Ignore = " ",
      Rename = " ",
      Diff = " ",
      Repo = " ",
      Octoface = " ",
    },
    ui = {
      ArrowClosed = "",
      ArrowOpen = "",
      Lock = " ",
      Circle = " ",
      BigCircle = " ",
      BigUnfilledCircle = " ",
      Close = " ",
      NewFile = " ",
      Search = " ",
      Lightbulb = " ",
      Project = " ",
      Dashboard = " ",
      History = " ",
      Comment = " ",
      Bug = " ",
      Code = " ",
      Telescope = " ",
      Gear = " ",
      Package = " ",
      List = " ",
      SignIn = " ",
      SignOut = " ",
      NoteBook = " ",
      Check = " ",
      Fire = " ",
      Note = " ",
      BookMark = " ",
      Pencil = " ",
      ChevronRight = "",
      Table = " ",
      Calendar = " ",
      CloudDownload = " ",
    },
    diagnostics = {
      Error = " ",
      Warning = " ",
      Information = " ",
      Question = " ",
      Hint = " ",
    },
    misc = {
      Robot = " ",
      Squirrel = " ",
      Tag = " ",
      Watch = " ",
      Smiley = " ",
      Package = " ",
      CircuitBoard = " ",
    },
  }
end
